name: device_info_plus_windows
description: Windows implementation of the device_info_plus plugin
version: 0.1.0
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.4'

dependencies:
  device_info_plus_platform_interface: ^0.3.0
  ffi: ^0.1.3
  flutter:
    sdk: flutter
  win32: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
